# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: effects.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import functions_pb2 as functions__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='effects.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\reffects.proto\x1a\x0f\x66unctions.proto\"&\n\x03HSV\x12\t\n\x01h\x18\x01 \x01(\x02\x12\t\n\x01s\x18\x02 \x01(\x02\x12\t\n\x01v\x18\x03 \x01(\x02\"-\n\x16\x43onstColorEffectConfig\x12\x13\n\x05\x63olor\x18\x01 \x01(\x0b\x32\x04.HSV\"Y\n\x13RainbowEffectConfig\x12!\n\thue_start\x18\x01 \x01(\x0b\x32\x0e.FloatFunction\x12\x1f\n\x07hue_end\x18\x02 \x01(\x0b\x32\x0e.FloatFunction\"\xe9\x01\n\x06\x45\x66\x66\x65\x63t\x12\x12\n\nstart_time\x18\x01 \x01(\x02\x12\x10\n\x08\x65nd_time\x18\x02 \x01(\x02\x12\x10\n\x08segments\x18\x03 \x03(\t\x12\x13\n\x0brepeat_time\x18\x04 \x01(\x02\x12\x14\n\x0crepeat_start\x18\x05 \x01(\x02\x12\x12\n\nrepeat_end\x18\x06 \x01(\x02\x12.\n\x0b\x63onst_color\x18\n \x01(\x0b\x32\x17.ConstColorEffectConfigH\x00\x12\'\n\x07rainbow\x18\x0b \x01(\x0b\x32\x14.RainbowEffectConfigH\x00\x42\x0f\n\reffect_config\"c\n\tAnimation\x12\x15\n\repoch_time_ms\x18\x01 \x01(\x04\x12\x10\n\x08\x64uration\x18\x02 \x01(\x02\x12\x13\n\x0bnum_repeats\x18\x03 \x01(\r\x12\x18\n\x07\x65\x66\x66\x65\x63ts\x18\x04 \x03(\x0b\x32\x07.Effectb\x06proto3')
  ,
  dependencies=[functions__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_HSV = _descriptor.Descriptor(
  name='HSV',
  full_name='HSV',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='h', full_name='HSV.h', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='s', full_name='HSV.s', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='v', full_name='HSV.v', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=72,
)


_CONSTCOLOREFFECTCONFIG = _descriptor.Descriptor(
  name='ConstColorEffectConfig',
  full_name='ConstColorEffectConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='color', full_name='ConstColorEffectConfig.color', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=74,
  serialized_end=119,
)


_RAINBOWEFFECTCONFIG = _descriptor.Descriptor(
  name='RainbowEffectConfig',
  full_name='RainbowEffectConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='hue_start', full_name='RainbowEffectConfig.hue_start', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='hue_end', full_name='RainbowEffectConfig.hue_end', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=121,
  serialized_end=210,
)


_EFFECT = _descriptor.Descriptor(
  name='Effect',
  full_name='Effect',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='start_time', full_name='Effect.start_time', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='end_time', full_name='Effect.end_time', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='segments', full_name='Effect.segments', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='repeat_time', full_name='Effect.repeat_time', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='repeat_start', full_name='Effect.repeat_start', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='repeat_end', full_name='Effect.repeat_end', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='const_color', full_name='Effect.const_color', index=6,
      number=10, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rainbow', full_name='Effect.rainbow', index=7,
      number=11, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='effect_config', full_name='Effect.effect_config',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=213,
  serialized_end=446,
)


_ANIMATION = _descriptor.Descriptor(
  name='Animation',
  full_name='Animation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='epoch_time_ms', full_name='Animation.epoch_time_ms', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='duration', full_name='Animation.duration', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='num_repeats', full_name='Animation.num_repeats', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='effects', full_name='Animation.effects', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=448,
  serialized_end=547,
)

_CONSTCOLOREFFECTCONFIG.fields_by_name['color'].message_type = _HSV
_RAINBOWEFFECTCONFIG.fields_by_name['hue_start'].message_type = functions__pb2._FLOATFUNCTION
_RAINBOWEFFECTCONFIG.fields_by_name['hue_end'].message_type = functions__pb2._FLOATFUNCTION
_EFFECT.fields_by_name['const_color'].message_type = _CONSTCOLOREFFECTCONFIG
_EFFECT.fields_by_name['rainbow'].message_type = _RAINBOWEFFECTCONFIG
_EFFECT.oneofs_by_name['effect_config'].fields.append(
  _EFFECT.fields_by_name['const_color'])
_EFFECT.fields_by_name['const_color'].containing_oneof = _EFFECT.oneofs_by_name['effect_config']
_EFFECT.oneofs_by_name['effect_config'].fields.append(
  _EFFECT.fields_by_name['rainbow'])
_EFFECT.fields_by_name['rainbow'].containing_oneof = _EFFECT.oneofs_by_name['effect_config']
_ANIMATION.fields_by_name['effects'].message_type = _EFFECT
DESCRIPTOR.message_types_by_name['HSV'] = _HSV
DESCRIPTOR.message_types_by_name['ConstColorEffectConfig'] = _CONSTCOLOREFFECTCONFIG
DESCRIPTOR.message_types_by_name['RainbowEffectConfig'] = _RAINBOWEFFECTCONFIG
DESCRIPTOR.message_types_by_name['Effect'] = _EFFECT
DESCRIPTOR.message_types_by_name['Animation'] = _ANIMATION

HSV = _reflection.GeneratedProtocolMessageType('HSV', (_message.Message,), dict(
  DESCRIPTOR = _HSV,
  __module__ = 'effects_pb2'
  # @@protoc_insertion_point(class_scope:HSV)
  ))
_sym_db.RegisterMessage(HSV)

ConstColorEffectConfig = _reflection.GeneratedProtocolMessageType('ConstColorEffectConfig', (_message.Message,), dict(
  DESCRIPTOR = _CONSTCOLOREFFECTCONFIG,
  __module__ = 'effects_pb2'
  # @@protoc_insertion_point(class_scope:ConstColorEffectConfig)
  ))
_sym_db.RegisterMessage(ConstColorEffectConfig)

RainbowEffectConfig = _reflection.GeneratedProtocolMessageType('RainbowEffectConfig', (_message.Message,), dict(
  DESCRIPTOR = _RAINBOWEFFECTCONFIG,
  __module__ = 'effects_pb2'
  # @@protoc_insertion_point(class_scope:RainbowEffectConfig)
  ))
_sym_db.RegisterMessage(RainbowEffectConfig)

Effect = _reflection.GeneratedProtocolMessageType('Effect', (_message.Message,), dict(
  DESCRIPTOR = _EFFECT,
  __module__ = 'effects_pb2'
  # @@protoc_insertion_point(class_scope:Effect)
  ))
_sym_db.RegisterMessage(Effect)

Animation = _reflection.GeneratedProtocolMessageType('Animation', (_message.Message,), dict(
  DESCRIPTOR = _ANIMATION,
  __module__ = 'effects_pb2'
  # @@protoc_insertion_point(class_scope:Animation)
  ))
_sym_db.RegisterMessage(Animation)


# @@protoc_insertion_point(module_scope)
