# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: segments.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='segments.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0esegments.proto\".\n\rSegmentConfig\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07indices\x18\x02 \x03(\r\"]\n\x11SegmentsMapConfig\x12\x0c\n\x04guid\x18\x01 \x01(\x07\x12\x18\n\x10number_of_pixels\x18\x02 \x01(\r\x12 \n\x08segments\x18\x03 \x03(\x0b\x32\x0e.SegmentConfigb\x06proto3'
)




_SEGMENTCONFIG = _descriptor.Descriptor(
  name='SegmentConfig',
  full_name='SegmentConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='SegmentConfig.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='indices', full_name='SegmentConfig.indices', index=1,
      number=2, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=64,
)


_SEGMENTSMAPCONFIG = _descriptor.Descriptor(
  name='SegmentsMapConfig',
  full_name='SegmentsMapConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='guid', full_name='SegmentsMapConfig.guid', index=0,
      number=1, type=7, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='number_of_pixels', full_name='SegmentsMapConfig.number_of_pixels', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='segments', full_name='SegmentsMapConfig.segments', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=66,
  serialized_end=159,
)

_SEGMENTSMAPCONFIG.fields_by_name['segments'].message_type = _SEGMENTCONFIG
DESCRIPTOR.message_types_by_name['SegmentConfig'] = _SEGMENTCONFIG
DESCRIPTOR.message_types_by_name['SegmentsMapConfig'] = _SEGMENTSMAPCONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SegmentConfig = _reflection.GeneratedProtocolMessageType('SegmentConfig', (_message.Message,), {
  'DESCRIPTOR' : _SEGMENTCONFIG,
  '__module__' : 'segments_pb2'
  # @@protoc_insertion_point(class_scope:SegmentConfig)
  })
_sym_db.RegisterMessage(SegmentConfig)

SegmentsMapConfig = _reflection.GeneratedProtocolMessageType('SegmentsMapConfig', (_message.Message,), {
  'DESCRIPTOR' : _SEGMENTSMAPCONFIG,
  '__module__' : 'segments_pb2'
  # @@protoc_insertion_point(class_scope:SegmentsMapConfig)
  })
_sym_db.RegisterMessage(SegmentsMapConfig)


# @@protoc_insertion_point(module_scope)
