/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.3 */

#ifndef PB_EFFECTS_PB_H_INCLUDED
#define PB_EFFECTS_PB_H_INCLUDED
#include <pb.h>
#include "functions.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _RainbowEffectConfig {
    pb_callback_t hue_start;
    pb_callback_t hue_end;
} RainbowEffectConfig;

typedef struct _Animation {
    uint64_t epoch_time_ms;
    float duration;
    uint32_t num_repeats;
    pb_callback_t effects;
} Animation;

typedef struct _HSV {
    float h;
    float s;
    float v;
} HSV;

typedef struct _ConstColorEffectConfig {
    bool has_color;
    HSV color;
} ConstColorEffectConfig;

typedef struct _Effect {
    float start_time;
    float end_time;
    pb_callback_t segments;
    float repeat_time;
    float repeat_start;
    float repeat_end;
    pb_size_t which_effect_config;
    union {
        ConstColorEffectConfig const_color;
        RainbowEffectConfig rainbow;
    } effect_config;
} Effect;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define HSV_init_default                         {0, 0, 0}
#define ConstColorEffectConfig_init_default      {false, HSV_init_default}
#define RainbowEffectConfig_init_default         {{{NULL}, NULL}, {{NULL}, NULL}}
#define Effect_init_default                      {0, 0, {{NULL}, NULL}, 0, 0, 0, 0, {ConstColorEffectConfig_init_default}}
#define Animation_init_default                   {0, 0, 0, {{NULL}, NULL}}
#define HSV_init_zero                            {0, 0, 0}
#define ConstColorEffectConfig_init_zero         {false, HSV_init_zero}
#define RainbowEffectConfig_init_zero            {{{NULL}, NULL}, {{NULL}, NULL}}
#define Effect_init_zero                         {0, 0, {{NULL}, NULL}, 0, 0, 0, 0, {ConstColorEffectConfig_init_zero}}
#define Animation_init_zero                      {0, 0, 0, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define RainbowEffectConfig_hue_start_tag        1
#define RainbowEffectConfig_hue_end_tag          2
#define Animation_epoch_time_ms_tag              1
#define Animation_duration_tag                   2
#define Animation_num_repeats_tag                3
#define Animation_effects_tag                    4
#define HSV_h_tag                                1
#define HSV_s_tag                                2
#define HSV_v_tag                                3
#define ConstColorEffectConfig_color_tag         1
#define Effect_start_time_tag                    1
#define Effect_end_time_tag                      2
#define Effect_segments_tag                      3
#define Effect_repeat_time_tag                   4
#define Effect_repeat_start_tag                  5
#define Effect_repeat_end_tag                    6
#define Effect_const_color_tag                   10
#define Effect_rainbow_tag                       11

/* Struct field encoding specification for nanopb */
#define HSV_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    h,                 1) \
X(a, STATIC,   SINGULAR, FLOAT,    s,                 2) \
X(a, STATIC,   SINGULAR, FLOAT,    v,                 3)
#define HSV_CALLBACK NULL
#define HSV_DEFAULT NULL

#define ConstColorEffectConfig_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  color,             1)
#define ConstColorEffectConfig_CALLBACK NULL
#define ConstColorEffectConfig_DEFAULT NULL
#define ConstColorEffectConfig_color_MSGTYPE HSV

#define RainbowEffectConfig_FIELDLIST(X, a) \
X(a, CALLBACK, OPTIONAL, MESSAGE,  hue_start,         1) \
X(a, CALLBACK, OPTIONAL, MESSAGE,  hue_end,           2)
#define RainbowEffectConfig_CALLBACK pb_default_field_callback
#define RainbowEffectConfig_DEFAULT NULL
#define RainbowEffectConfig_hue_start_MSGTYPE FloatFunction
#define RainbowEffectConfig_hue_end_MSGTYPE FloatFunction

#define Effect_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    start_time,        1) \
X(a, STATIC,   SINGULAR, FLOAT,    end_time,          2) \
X(a, CALLBACK, REPEATED, STRING,   segments,          3) \
X(a, STATIC,   SINGULAR, FLOAT,    repeat_time,       4) \
X(a, STATIC,   SINGULAR, FLOAT,    repeat_start,      5) \
X(a, STATIC,   SINGULAR, FLOAT,    repeat_end,        6) \
X(a, STATIC,   ONEOF,    MESSAGE,  (effect_config,const_color,effect_config.const_color),  10) \
X(a, STATIC,   ONEOF,    MESSAGE,  (effect_config,rainbow,effect_config.rainbow),  11)
#define Effect_CALLBACK pb_default_field_callback
#define Effect_DEFAULT NULL
#define Effect_effect_config_const_color_MSGTYPE ConstColorEffectConfig
#define Effect_effect_config_rainbow_MSGTYPE RainbowEffectConfig

#define Animation_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   epoch_time_ms,     1) \
X(a, STATIC,   SINGULAR, FLOAT,    duration,          2) \
X(a, STATIC,   SINGULAR, UINT32,   num_repeats,       3) \
X(a, CALLBACK, REPEATED, MESSAGE,  effects,           4)
#define Animation_CALLBACK pb_default_field_callback
#define Animation_DEFAULT NULL
#define Animation_effects_MSGTYPE Effect

extern const pb_msgdesc_t HSV_msg;
extern const pb_msgdesc_t ConstColorEffectConfig_msg;
extern const pb_msgdesc_t RainbowEffectConfig_msg;
extern const pb_msgdesc_t Effect_msg;
extern const pb_msgdesc_t Animation_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define HSV_fields &HSV_msg
#define ConstColorEffectConfig_fields &ConstColorEffectConfig_msg
#define RainbowEffectConfig_fields &RainbowEffectConfig_msg
#define Effect_fields &Effect_msg
#define Animation_fields &Animation_msg

/* Maximum encoded size of messages (where known) */
#define HSV_size                                 15
#define ConstColorEffectConfig_size              17
/* RainbowEffectConfig_size depends on runtime parameters */
/* Effect_size depends on runtime parameters */
/* Animation_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
