/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.3 */

#ifndef PB_KIVSEE_PROTO_SEGMENTS_PB_H_INCLUDED
#define PB_KIVSEE_PROTO_SEGMENTS_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _kivsee_proto_Pixel {
    uint32_t index;
    float rel_pos;
} kivsee_proto_Pixel;

typedef struct _kivsee_proto_Segment {
    char name[10];
    pb_callback_t pixels;
} kivsee_proto_Segment;

typedef struct _kivsee_proto_ThingSegments {
    uint32_t guid;
    uint32_t number_of_pixels;
    pb_callback_t segments;
} kivsee_proto_ThingSegments;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define kivsee_proto_Pixel_init_default          {0, 0}
#define kivsee_proto_Segment_init_default        {"", {{NULL}, NULL}}
#define kivsee_proto_ThingSegments_init_default  {0, 0, {{NULL}, NULL}}
#define kivsee_proto_Pixel_init_zero             {0, 0}
#define kivsee_proto_Segment_init_zero           {"", {{NULL}, NULL}}
#define kivsee_proto_ThingSegments_init_zero     {0, 0, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define kivsee_proto_Pixel_index_tag             1
#define kivsee_proto_Pixel_rel_pos_tag           2
#define kivsee_proto_Segment_name_tag            1
#define kivsee_proto_Segment_pixels_tag          2
#define kivsee_proto_ThingSegments_guid_tag      1
#define kivsee_proto_ThingSegments_number_of_pixels_tag 2
#define kivsee_proto_ThingSegments_segments_tag  3

/* Struct field encoding specification for nanopb */
#define kivsee_proto_Pixel_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   index,             1) \
X(a, STATIC,   SINGULAR, FLOAT,    rel_pos,           2)
#define kivsee_proto_Pixel_CALLBACK NULL
#define kivsee_proto_Pixel_DEFAULT NULL

#define kivsee_proto_Segment_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   name,              1) \
X(a, CALLBACK, REPEATED, MESSAGE,  pixels,            2)
#define kivsee_proto_Segment_CALLBACK pb_default_field_callback
#define kivsee_proto_Segment_DEFAULT NULL
#define kivsee_proto_Segment_pixels_MSGTYPE kivsee_proto_Pixel

#define kivsee_proto_ThingSegments_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FIXED32,  guid,              1) \
X(a, STATIC,   SINGULAR, UINT32,   number_of_pixels,   2) \
X(a, CALLBACK, REPEATED, MESSAGE,  segments,          3)
#define kivsee_proto_ThingSegments_CALLBACK pb_default_field_callback
#define kivsee_proto_ThingSegments_DEFAULT NULL
#define kivsee_proto_ThingSegments_segments_MSGTYPE kivsee_proto_Segment

extern const pb_msgdesc_t kivsee_proto_Pixel_msg;
extern const pb_msgdesc_t kivsee_proto_Segment_msg;
extern const pb_msgdesc_t kivsee_proto_ThingSegments_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define kivsee_proto_Pixel_fields &kivsee_proto_Pixel_msg
#define kivsee_proto_Segment_fields &kivsee_proto_Segment_msg
#define kivsee_proto_ThingSegments_fields &kivsee_proto_ThingSegments_msg

/* Maximum encoded size of messages (where known) */
#define kivsee_proto_Pixel_size                  11
/* kivsee_proto_Segment_size depends on runtime parameters */
/* kivsee_proto_ThingSegments_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
