/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.3 */

#include "effects.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(HSV, HSV, AUTO)


PB_BIND(ConstColorEffectConfig, ConstColorEffectConfig, AUTO)


PB_BIND(RainbowEffectConfig, RainbowEffectConfig, AUTO)


PB_BIND(Effect, Effect, AUTO)


PB_BIND(Animation, Animation, AUTO)



