/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.3 */

#include "functions.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(ConstValueFloatFunctionConfig, ConstValueFloatFunctionConfig, AUTO)


PB_BIND(LinearFloatFunctionConfig, LinearFloatFunctionConfig, AUTO)


PB_BIND(SinFloatFunctionConfig, SinFloatFunctionConfig, AUTO)


PB_BIND(StepsFloatFunctionConfig, StepsFloatFunctionConfig, AUTO)


PB_BIND(RepeatFloatFunctionConfig, RepeatFloatFunctionConfig, AUTO)


PB_BIND(HalfFloatFunctionConfig, HalfFloatFunctionConfig, AUTO)


PB_BIND(Comb2FloatFunctionConfig, Comb2FloatFunctionConfig, AUTO)


PB_BIND(FloatFunction, FloatFunction, AUTO)



