/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9 */

#include "segments.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(kivsee_proto_Pixel, kivsee_proto_Pixel, AUTO)


PB_BIND(kivsee_proto_Segment, kivsee_proto_Segment, AUTO)


PB_BIND(kivsee_proto_ThingSegments, kivsee_proto_ThingSegments, AUTO)



