name: Build simulation service

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-service:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup cmake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: "3.28.1"

      - name: build simulation service
        run: |
          mkdir build
          cd build
          cmake ..
          cmake --build .
