name: Build simulation service

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-service:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup cmake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: "4.0.2"

      - name: build simulation service
        working-directory: simulation-service
        run: |
          mkdir -p build
          cmake -S . -B build
          cmake --build build
