name: Release Python Bindings

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [x86_64, aarch64, armv7]
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Bazelisk
        uses: bazelbuild/setup-bazelisk@v2

      - name: Build Python bindings
        run: |
          bazel build //bindings:kivsee_render_linux_${{ matrix.arch }}
          mkdir -p dist
          cp bazel-bin/bindings/kivsee_render_linux_${{ matrix.arch }}.so dist/

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-${{ matrix.arch }}-bindings
          path: dist/

  build-macos:
    runs-on: macos-latest
    strategy:
      matrix:
        arch: [x86_64, arm64]
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Bazelisk
        uses: bazelbuild/setup-bazelisk@v2

      - name: Build Python bindings
        run: |
          bazel build //bindings:kivsee_render_macos_${{ matrix.arch }}
          mkdir -p dist
          cp bazel-bin/bindings/kivsee_render_macos_${{ matrix.arch }}.so dist/

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macos-${{ matrix.arch }}-bindings
          path: dist/

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Bazelisk
        uses: bazelbuild/setup-bazelisk@v2

      - name: Build Python bindings
        run: |
          bazel build //bindings:kivsee_render_windows_x86_64
          mkdir -p dist
          cp bazel-bin/bindings/kivsee_render_windows_x86_64.dll dist/

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-x86_64-bindings
          path: dist/

  create-release:
    needs: [build-linux, build-macos, build-windows]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist
          merge-multiple: true

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*.so
            dist/*.dll
          draft: false
          prerelease: false
          generate_release_notes: true 