on:
    push:
      branches:
        - master
    pull_request:
      branches:
        - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup bazel
        uses: jwlawson/actions-setup-bazel@v1
        with:
          bazel-version: '4.1.0'        

      - name: Run tests
        run: bazel test --test_output=all //test:kivsee-render-test