on:
    push:
      branches:
        - main
    pull_request:
      branches:
        - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup bazel
        uses: jwlawson/actions-setup-bazel@v1
        with:
          bazel-version: '6.4.0'        

      - name: Run tests
        run: bazel test --test_output=all //test:kivsee-render-test